### PR TITLE
Add BitDevs Oslo to Cities?

### PR DESCRIPTION
**Pull request by Tobben67**
BitDevs Oslo is born. Will you consider adding BitDevs Oslo to Cities?

BitDevs Oslo Meetup page:
https://www.meetup.com/bitcoin-developers-oslo/

First event:
https://www.meetup.com/bitcoin-developers-oslo/events/299290841/

Second event:
https://www.meetup.com/bitcoin-developers-oslo/events/299810289/

We hope to see as many participants as possible at BitDevs Oslo June 3, 2024. This is the same day that [The Oslo Freedom Forum by HRF](https://oslofreedomforum.com) Starts. [niftynei](https://opensats.org/about/niftynei) has already accepted giving a presentation for The Socratic Seminar @ BitDevs Oslo June 3, 2024.

Best regards from
[Satoshi Consult](https://twitter.com/satoshiconsult) and [Bare Bitcoin](https://twitter.com/barebitcoin)

### CODE REVIEW

**Comment by btsea** [comment]
Thanks for the PR @Tobben67! Our only constraint on inclusion is that the meetup has had at least one socratic seminar and has a second planned. Is that the case here? I can't quite grok given the language barrier. 

If that requirement is satisfied I am happy to merge this. 

Thank you again.

**Comment by Tobben67** [comment]
I'm grateful for your response, @btsea 

I can confirm that both events have been socratic seminars. This has at least been the goal of BitDevs Oslo. In our last socratic seminar on April 8, BitDevs Oslo had approximately 1 hour of group-discussions on different Covenants-proposals.

One of the co-organizers of BitDevs Oslo regularly participates digitally in the socratic seminars arranged by [BitDevs Berlin](https://bitdevs.berlin).

BitDevs Oslo is inspired by [Running a Great Socratic Seminar](https://bitdevs.org/running-a-great-socratic-seminar/)

Satoshi Consult and Bare Bitcoin also have a plan acquiring a domain for BitDevs Oslo so that we can host our own BitDevs Oslo website.

BitDevs Oslo is the succession of OsloPlebs:
OsloPlebs May
OsloPlebs September

Best regards from Norway

**Comment by btsea** [comment]
Hey @Tobben67 I have added Oslo to the cities, linking directly to the meetup page: https://github.com/BitDevsNYC/BitDevsNYC.github.io/commit/64775f8146bc72546f57685cb3a088c84c312aad

If you want me to link to your link aggregation site, please let me know and we can do that. I saw a lot of unrelated changes in this PR so I am not going to merge it. I'll close it for now, and once you have your site up feel free to open another PR!

Excited for you and wishing you all the best in Oslo. Please drop a line if you are ever in the states!

**Comment by Tobben67** [comment]
> Hey @Tobben67 I have added Oslo to the cities, linking directly to the meetup page: [64775f8](https://github.com/BitDevsNYC/BitDevsNYC.github.io/commit/64775f8146bc72546f57685cb3a088c84c312aad)
> 
> If you want me to link to your link aggregation site, please let me know and we can do that. I saw a lot of unrelated changes in this PR so I am not going to merge it. I'll close it for now, and once you have your site up feel free to open another PR!
> 
> Excited for you and wishing you all the best in Oslo. Please drop a line if you are ever in the states!

I'm very grateful, @btsea 

I just broadcasted [the 3rd Socratic Seminar @ BitDevs Oslo on meetup](https://www.meetup.com/bitcoin-developers-oslo/events/300712132/). This time in English.

Best regards from Oslo

**Pull request closed without merging**
