### PR TITLE
Collate source links

### PR DESCRIPTION
**Pull request by btsea**
This is just a dump of links--unsorted and without descriptions for now until we decide what exactly we want to do with this page.

### CODE REVIEW

**Comment by jnewbery** [comment]
Concept ACK!

**Comment by jnewbery** [comment]
@btsea - I've made a few changes. Let me know what you think:

- change name to `sources`, so the url is https://bitdevsnyc.org/sources. I think that's shorted and easier to remember.
- add short introductory text
- change text to links

I also think we should add a short description to each link. I've done that for the first. If you agree, do you mind adding descriptions to the other links?

Other potential enhancements:

- add subsections (for mempool, mining, etc)
- put this all in a yaml data file and generate the page from the data file. That might make it a bit friendlier to update and maintain.

**Comment by jnewbery** [comment]
@btsea - I've added a commit that moves the source data to its own yml file. That should be easier to maintain. What do you think?

(I've only done it for the first two links. If you agree that this is a better approach, do you mind moving the rest?)

**Comment by jnewbery** [comment]
@btsea are you planning to work on this again? If not, let's close the PR.

**Comment by btsea** [comment]
Hmm, totally forgot about it. Give me another week, if nothing then we close it.

**Comment by jnewbery** [comment]
> Hmm, totally forgot about it

Yeah, 2020 happened :laughing:

**Comment by btsea** [comment]
Closing for another day, another time.

**Pull request closed without merging**
