### PR TITLE
Rules for presenters

### PR DESCRIPTION
**Pull request by btsea**
First pass on suggested rules for presentations.

### CODE REVIEW

**Comment by andrerfneves** [comment]
@btsea looks good to me. I think the change to 12min/5min is great.

**Comment by jnewbery** [comment]
> I think the change to 12min/5min is great.

I don't understand this. Why do we want to tell the presenter how much time they should spend on the presentation and how much on q&a? Can't we just say '15 minutes including q&a' and let the presenter decide how they fill the time?

**Comment by btsea** [comment]
@jnewbery I don't have a strong attachment to the way I worded it. Historically that is how I have communicated the time limits, but if it is unnecessarily constraining it can be removed. 

@adamjonas Yes I like that idea.

**Comment by jnewbery** [comment]
@btsea - see #49 where this is incorporated into the bitdevs site.

**Comment by jnewbery** [comment]
Merged in #49

**Pull request closed without merging**
